### PR TITLE
Use the variables as color data.

### LINKED ISSUE #99: Default theme is using hard coded values for the theme colors.
It adds extra sync maintenance work.

### PR DESCRIPTION
**Pull request by diogocamposwd**
Fixes #99

### CODE REVIEW

**Comment by addyosmani** [comment]
It looks like the static version of these color values was added back in https://github.com/PolymerElements/paper-styles/commit/2d1706d2be5116bafae1816982035bb106e929a1. It would probably be good to check with @notwaldorf if there was a reason this was preferred to using the variables directly.

**Comment by diogocamposwd** [comment]
Commit referenced doesn't seem related.

**Comment by notwaldorf** [comment]
Looking at the file, all of the values seem to be hardcoded, and not pulled from `color.html`. I feel if we want to change them, maybe we should change all of them?

**Comment by notwaldorf** [comment]
This PR is looking good, but it needs a rebase before it can be merged. I'm going to close it for now, but please re-open it after you have performed a rebase!

**Pull request closed without merging**
