### PR TITLE
added --error-color

### PR DESCRIPTION
**Pull request by IntranetFactory**
based on https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors and discussed in https://github.com/PolymerElements/paper-styles/issues/94

### CODE REVIEW

**Comment by IntranetFactory** [comment]
I signed it!

**Comment by BartKoppelmans** [comment]
I think you should reply on GitHub, not via email ;)

**Comment by notwaldorf** [comment]
@IntranetFactory Yeah, you have to respond via the GitHub UI, please :)

**Comment by IntranetFactory** [comment]
I signed it!

**Comment by notwaldorf** [comment]
Thanks!

**Pull request merged**
