### PR TITLE
Include typography in demo-pages.html

### PR DESCRIPTION
**Pull request by blasten**
cc @cdata @morethanreal @notwaldorf

### CODE REVIEW

**Comment by notwaldorf** [comment]
Is this so that we don't have to include `paper-styles.html` all the time? In that case, do you think it should include `iron-flex-layout` as well?

**Comment by blasten** [comment]
@notwaldorf I think so because most demos have to import `paper-styles.html` in order to use  `demo.html`. what do you think?

**Comment by notwaldorf** [comment]
Ok, then let's add both and try to remove `paper-styles` whenever we see them (the won't get imported twice since they're on the same page, so it's not a big deal for the past demos)

**Comment by blasten** [comment]
@notwaldorf I have included `paper-styles.html` directly.

**Comment by notwaldorf** [comment]
Isn't that a bit much, though? Like we're including `default-theme`, which isn't being used, and both the mixin and not mixin versions of `iron-flex-layout`. I realized we were doing this in a demo, but we technically didn't have to (we should just include the 3 things we need). /cc @morethanreal in case i'm overthinking this.

**Comment by blasten** [comment]
@notwaldorf PTAL

**Comment by notwaldorf** [comment]
Awesome! lgtm

**Comment by addyosmani** [comment]
:+1:

**Pull request merged**
