### PR TITLE
remove extra font stylesheets

### PR DESCRIPTION
**Pull request by azakus**

### CODE REVIEW

**Comment by azakus** [comment]
Fixes #22
Fixes #39

**Comment by cdata** [comment]
Does Material Design recommend anything in particular about monospace fonts?

Otherwise, LGTM :+1:

**Comment by azakus** [comment]
There is https://www.google.com/fonts/specimen/Roboto+Mono

**Comment by cdata** [comment]
Should we have a `roboto-mono.html`?

**Comment by azakus** [comment]
Yeah I think so. I'll open a PR for font-roboto to cover that.

**Comment by azakus** [comment]
I assume just for 400 and 700 font weight like how we were loading Inconsolata

**Comment by azakus** [comment]
Done. PTAL

**Comment by cdata** [comment]
LGTM :+1:

**Pull request merged**
