### PR TITLE
Remove deprecated shadow layout

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by notwaldorf** [comment]
Oh, no, this isn't something we can do :( We can't delete any code like this, deprecated or not, because we don't have any guarantees that it isn't being used by anyone. It's an enormous breaking change.

We don't have a good plan about what to do to deal with the `/deep/` deprecation, but deleting the code isn't a solution :(

**Comment by abdonrd** [comment]
@notwaldorf in this commit https://github.com/PolymerElements/paper-styles/commit/9260636e30c737cc297db305255d739b11102618 you said "will be deleted on October 1st, 2015". :sweat_smile:

**Comment by notwaldorf** [comment]
Huh, so I did. 
@cdata, what do you think? (For context, this isn't changing `iron-flex-layout`, this is just deleting a super weird file in `paper-styles` that is basically a duplicate of the shadow classes in `iron-flex-layout`. I think it's left over in `paper-styles` since before we had made `iron-flex-layout`)

**Comment by addyosmani** [comment]
FYI list of projects referencing this in GitHub code search: https://github.com/search?q=classes%2Fshadow-layout.html&type=Code&utf8=%E2%9C%93

**Comment by notwaldorf** [comment]
@addyosmani That's a horrifying bunch of search results 😭

**Comment by abdonrd** [comment]
@notwaldorf @addyosmani then we ignore the https://github.com/PolymerElements/paper-styles/commit/9260636e30c737cc297db305255d739b11102618 and close this PR?

**Comment by BartKoppelmans** [comment]
Sooo, this file won't be deleted? Is there any other way to prevent the `/deep/'-warning from showing up?

**Comment by abdonrd** [comment]
@BartKoppelmans don't use /deep/, use mixins. All information: https://blog.polymer-project.org/announcements/2015/08/13/1.1-release/

**Comment by BartKoppelmans** [comment]
I have already stopped using the /deep/. There still is a warning, I figured it came from the shadow-layout.html file.

PS: I think you meant https://blog.polymer-project.org/announcements/2015/12/01/deprecating-deep/ ;)

**Comment by abdonrd** [comment]
@BartKoppelmans oops! I paste the wrong link! :sweat_smile: Edited.

Where do you import the `shadow-layout.html`? You shouldn't use the files of the "classes" directory.

**Comment by BartKoppelmans** [comment]
I removed it already from my imports. I'm still getting the warning, even though i get 0 results when I search my directory for /deep/. This is weird. Must be me missing something. Thanks for the help anyway :smile:

**Comment by notwaldorf** [comment]
I'm going to close this PR, since we can't merge it. We'll address all the things in the 2.0 version of the element.

**Pull request closed without merging**
