### PR TITLE
Include demo-pages.html

### PR DESCRIPTION
**Pull request by blasten**
Most demo pages are using the classes `horizontal`,`center-justified`,`layout`

### CODE REVIEW

**Comment by notwaldorf** [comment]
Hmm, why is this needed? The code in that file doesn't use any of the classes.

**Comment by notwaldorf** [comment]
(didn't mean to close the PR, just comment on it)

**Comment by blasten** [comment]
@notwaldorf the demo files use classes https://github.com/PolymerElements/paper-menu/blob/master/demo/index.html#L43

we are still including `paper-styles.html` https://github.com/PolymerElements/paper-menu/blob/master/demo/index.html#L24

**Comment by notwaldorf** [comment]
Right, so if an `index.html` uses the classes, _it_ needs to import `iron-flex-layout/classes` (since `demo-pages.html` itself doesn't).

**Comment by blasten** [comment]
as discussed, demos should use `horizontal-section-container` & `vertical-section-container`

**Pull request closed without merging**
