### PR TITLE
Convert some colors from 'grey' to 'base+opacity'.

### LINKED ISSUE #97: Default theme should not use grey text.
The [spec](https://www.google.com/design/spec/style/color.html#color-ui-color-application) says:

> Use opacity for text, icons, and dividers
>
> You can change the opacity of text to convey how important certain information is relative to other text.
>
> Transparent black or white text behaves more flexibly than grey text because it remains legible and vibrant against background color changes.

### PR DESCRIPTION
**Pull request by diogocamposwd**
Fixes #97

### CODE REVIEW

**Comment by diogocamposwd** [comment]
Signed CLA.

**Comment by addyosmani** [comment]
Foot-note: I originally had concerns about applying opacity for these values. Based on an older convo with @paulirish "Opacity is one of the few CSS properties that can be properly accelerated because the GPU can manipulate it easily. ". If this is still the case, it may be worth a change like this making it for spec conformance.

**Comment by notwaldorf** [comment]
I'm relying on a recent discussion (https://github.com/PolymerElements/paper-styles/pull/74#issuecomment-161119927) between @blasted and the Blink team who said this is strictly more expensive than solid colours. If this is true, then I will push back on this PR (and any similar once), since spec conformity is not worth performance (in my opinion).

I would love if we wanted to profile or go into more details (but I don't quite have the bandwidth for that right now 😭).

**Comment by paulirish** [comment]
AFAIK, blink isn't smart enough to accelerate transitions between `hsl(0,0%,0%,0.1)` and  `hsl(0,0%,0%,0.9)`. Only the `opacity` property itself. (and `transform` obv).

So this wouldn't have perf benefits.

That said, [I'm a big HSL fan](http://mothereffinghsl.com/), so +1 to rewriting stupid hex as HSL! :D

**Comment by paulirish** [comment]
just read the thread w/ blasted.  the perf difference is probably pretty damn minimal. 

if the visual difference is noticeable, then its probably worth looking at the perf. the paint profiler in devtools would show it. my sense is it's tiny tiny fractions of a millisecond.

that said, applying opacity to body/secondary text seems crazy to my brain. sorry, material spec. so sorry.

**Comment by JosefJezek** [comment]
Text with opacity is readable. I tested it...

image

**Comment by notwaldorf** [comment]
> applying opacity to body/secondary text seems crazy to my brain
@paulirish soooo we should not do this, then? I'm not a giant fan of change for the sake of change, especially since we haven't done any profiling, and anything that comes with the "X is more expensive than not doing X" caveat isn't great.

I will go chase down some Blink folk again :)

**Comment by notwaldorf** [comment]
(Please don't merge this PR)

I've talked to @esprehn who agrees that transparent text will be more expensive than fully opaque text. He promised to add more details to this PR explaining that reasoning, and then we can probably closing.

**Comment by notwaldorf** [comment]
I'm going to close this PR since we aren't going to merge it, and I haven't managed to track down Elliott to leave a comment, but basically: he says that since we're adding opacity to the text, if we have to draw on top or below it it won't be able to get optimized and we'll have to do a lot of repaints.

**Pull request closed without merging**
